# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='addtime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AddField(
            model_name='actor',
            name='password',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='actor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Actor'),
            preserve_default=False,
        ),
    ]
