# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-30 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190330_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='title',
        ),
    ]
