# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-30 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='users',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
