# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_actor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
