# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-31 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190330_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[(1, '男'), (0, '女')], default='1', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('actor', 'patient', 'status')]),
        ),
    ]
