# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-31 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190331_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='patient',
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Order'),
            preserve_default=False,
        ),
    ]
