# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-17 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=6)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('permission', models.ManyToManyField(to='myadmin.Permission')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='Storied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('sex', models.CharField(choices=[(1, '男'), (0, '女')], max_length=1)),
                ('avatar', models.FileField(default='/static/myadmin/img/default.jpg', upload_to='static/myadmin/img/', verbose_name='头像')),
                ('speciality', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Dormitory')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('role', models.ManyToManyField(to='myadmin.Role')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no', models.CharField(max_length=50)),
                ('card', models.CharField(max_length=18)),
                ('dormitory', models.CharField(max_length=50)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='storied',
            name='storied',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
        ),
    ]
