# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-18 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
