# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_remove_dormitory_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(default='static/myadmin/assets/img/default.png', upload_to='static/myadmin/assets/img/', verbose_name='头像'),
        ),
    ]
