# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20190319_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(default='stu_img/default.png', upload_to='stu_img/', verbose_name='头像'),
        ),
    ]
